
---

end-date: 2015-11-01

milestones:
  - date: 2015-10-15
    label: Code Freeze
  - date: 2015-11-01
    label: GO Life

#
# configure content of chart sigma explicitly
# optional
#
charts-sigma:
  included-data:
    - open-issues
    - total issues


# growing index is different on different phases of a project
# smaller values indicates faster progress
factors:
  - 0.5 0.8
  - 0.7 1.0
  - 1.1 1.5
