
---

end-date: 2015-11-01

charts-sigma:
  included-data:
    - open-issues
    - total issues
    - testable-issues

# growing index is different on different phases of a project
# smaller values indicates faster progress
factors:
  - 0.5 0.8
  - 0.7 1.0
  - 1.1 1.5
